# See:
#   https://docs.helix-editor.com/master/languages.html
#   https://github.com/helix-editor/helix/blob/master/languages.toml

[[language]]
name = "rust"
auto-format = false

[language-server.rust-analyzer]
command = "rust-analyzer"

[language-server.rust-analyzer.config.check]
command = "clippy"
